services:
  pytorch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: highmorph
    tty: true

    # bindでcontainerにファイルをマウントさせる．
    volumes:
      - type: bind
        source: SemanticStyleGAN
        target: /root/work
    # ホストのport番号 : コンテナのport番号．Jupyter Lab（notebook)はデフォルトで8888番．
    ports:
      - "8080:8888"
    command:
      jupyter-lab --ip 0.0.0.0 --allow-root --NotebookApp.token=''
    runtime: nvidia

